webapp/config/routes.rb
Properties::Application.routes.draw do

  root :to => 'properties#index', :as => 'properties'
  match 'properties/rent' => 'properties#pesquisa', :defaults => { :rent => true }, :via => :get, :as => 'properties_rent'
  match 'properties/sell' => 'properties#pesquisa', :defaults => { :sell => true }, :via => :get, :as => 'properties_sell'

end

webapp/app/models/property.rb
class Property < ActiveRecord::Base

  has_many :property_images, :dependent => :destroy
  belongs_to :property_source
  attr_accessible :floors, :built_year, :agent, :area, :common_area, :neighborhood, :city, :trade_terms, :creci, :publish_date, :description, :bedroom, :images, :location, :number_of_suites, :number_of_parking_space, :other_things, :street, :phones, :type_of_property, :state, :rent_value, :maintenance_value, :square_meter, :sell_value, :url, :rent, :sell

end

webapp/app/models/property_image.rb
class PropertyImage < ActiveRecord::Base
  belongs_to :property
  attr_accessible :url
end

webapp/app/models/property_source.rb
class PropertySource < ActiveRecord::Base
  has_many :property, :dependent => :destroy
  attr_accessible :name, :url
end

webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

webapp/app/controllers/imoveis_controller.rb
#encoding: utf-8

class ImoveisController < ApplicationController

  def pesquisa
    @aluguel = params['aluguel']
    @venda = params['venda']

    params[:q] = {} unless params[:q]
    params[:q].store(:aluguel_true, '1') if @aluguel
    params[:q].store(:venda_true, '1') if @venda

    @search = Imovel.search(params[:q])
    @imoveis = @search.result
  end

end

webapp/app/controllers/properties_controller.rb
#encoding: utf-8

class PropertiesController < ApplicationController

  def pesquisa
    @rent = params['rent']
    @sell = params['sell']

    params[:q] = {} unless params[:q]
    params[:q].store(:rent_true, '1') if @rent
    params[:q].store(:sell_true, '1') if @sell

    @search = Property.search(params[:q])
    @properties = @search.result
  end

end

webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

webapp/app/helpers/properties_helper.rb
module PropertiesHelper
end

webapp/app/views/imoveis/pesquisa.html.haml
= search_form_for @search, :url => request.path do |f|
  .field
    = f.label :imovel_site_nome_eq, 'Site'
    = f.text_field :imovel_site_nome_eq
  .field
    = f.label :data_publicacao_gteq, 'Data de publicação maior ou maior que'
    = f.text_field :data_publicacao_gteq
  .field
    = f.label :data_publicacao_lteq, 'Data de publicação menor ou maior que'
    = f.text_field :data_publicacao_lteq
  .field
    = f.label :tipo_eq, 'Tipo é'
    = f.text_field :tipo_eq
  .field
    = f.label :cidade_eq, 'Cidade é'
    = f.text_field :cidade_eq
  .field
    = f.label :bairro_eq, 'Bairro é'
    = f.text_field :bairro_eq
  - if @venda
    .field
      = f.label :valor_venda_gteq, 'Valor da venda maior ou igual que'
      = f.text_field :valor_venda_gteq
    .field
      = f.label :valor_venda_lt, 'Valor da venda menor que'
      = f.text_field :valor_venda_lt
  - if @aluguel
    .field
      = f.label :valor_aluguel_gteq, 'Valor do aluguel maior ou igual que'
      = f.text_field :valor_aluguel_gteq
    .field
      = f.label :valor_aluguel_lteq, 'Valor do aluguel menor ou igual que'
      = f.text_field :valor_aluguel_lteq
  .field
    = f.label :valor_condominio_gteq, 'Valor do condomínio maior ou igual que'
    = f.text_field :valor_condominio_gteq
  .field
    = f.label :valor_condominio_lteq, 'Valor do condomínio menor ou igual que'
    = f.text_field :valor_condominio_lteq
  .field
    = f.label :area_util_gteq, 'Área útil maior ou igual que'
    = f.text_field :area_util_gteq
  .field
    = f.label :area_util_lteq, 'Área útil menor ou igual que'
    = f.text_field :area_util_lteq
  .field
    = f.label :dormitorios_gteq, 'Dormitórios maior ou igual que'
    = f.text_field :dormitorios_gteq
  .field
    = f.label :dormitorios_lteq, 'Dormitórios menor ou igual que'
    = f.text_field :dormitorios_lteq
  .field
    = f.label :numero_suites_gteq, 'Número de suites maior ou igual que'
    = f.text_field :numero_suites_gteq
  .field
    = f.label :numero_suites_lteq, 'Número de suítes menor ou igual que'
    = f.text_field :numero_suites_lteq
  .field
    = f.label :numero_vagas_gteq, 'Número de vagas maior ou igual que'
    = f.text_field :numero_vagas_gteq
  .field
    = f.label :numero_vagas_lteq, 'Número de vagas menor ou igual que'
    = f.text_field :numero_vagas_lteq
  .actions
    = f.submit 'Pesquisar'

%table.imoveis
  %thead
    %tr
      %th= sort_link @search, :imovel_site_nome, 'Site'
      %th= sort_link @search, :data_publicacao, 'Data'
      %th= sort_link @search, :tipo, 'Tipo'
      %th= sort_link @search, :cidade, 'Cidade'
      %th= sort_link @search, :bairro, 'Bairro'
      %th= sort_link @search, :valor_venda, 'Valor' if @venda
      %th= sort_link @search, :valor_aluguel, 'Valor' if @aluguel
      %th= sort_link @search, :valor_condominio, 'Condomínio'
      %th= sort_link @search, :area_util, 'Área'
      %th= sort_link @search, :dormitorios, 'Quartos'
      %th= sort_link @search, :numero_suites, 'Suítes'
      %th= sort_link @search, :numero_vagas, 'Vagas'
      %th
  %tbody
    - @imoveis.limit(100).each do |imovel|
      %tr
        %td= imovel.imovel_site.nome
        %td= imovel.data_publicacao
        %td= imovel.tipo
        %td= imovel.cidade
        %td= imovel.bairro
        %td= imovel.valor_venda
        %td= imovel.valor_aluguel
        %td= imovel.valor_condominio
        %td= imovel.area_util
        %td= imovel.dormitorios
        %td= imovel.numero_suites
        %td= imovel.numero_vagas
        %td
          %a{:href => '#'} Ver detalhes

webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Properties</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

webapp/app/views/properties/index.html.haml
.sell
  = link_to 'sell', properties_sell_path
.rent
  = link_to 'rent', properties_rent_path

webapp/app/views/properties/pesquisa.html.haml
= search_form_for @search, :url => request.path do |f|
  .field
    = f.label :property_source_name_eq, 'Site'
    = f.text_field :property_source_name_eq
  .field
    = f.label :publish_date_gteq, 'Data de publicação maior ou maior que'
    = f.text_field :publish_date_gteq
  .field
    = f.label :publish_date_lteq, 'Data de publicação menor ou maior que'
    = f.text_field :publish_date_lteq
  .field
    = f.label :type_of_property_eq, 'Tipo é'
    = f.text_field :type_of_property_eq
  .field
    = f.label :city_eq, 'Cidade é'
    = f.text_field :city_eq
  .field
    = f.label :neighborhood_eq, 'Bairro é'
    = f.text_field :neighborhood_eq
  - if @sell
    .field
      = f.label :sell_value_gteq, 'Valor da venda maior ou igual que'
      = f.text_field :sell_value_gteq
    .field
      = f.label :sell_value_lt, 'Valor da venda menor que'
      = f.text_field :sell_value_lt
  - if @rent
    .field
      = f.label :rent_value_gteq, 'Valor do aluguel maior ou igual que'
      = f.text_field :rent_value_gteq
    .field
      = f.label :rent_value_lteq, 'Valor do aluguel menor ou igual que'
      = f.text_field :rent_value_lteq
  .field
    = f.label :maintenance_value_gteq, 'Valor do condomínio maior ou igual que'
    = f.text_field :maintenance_value_gteq
  .field
    = f.label :maintenance_value_lteq, 'Valor do condomínio menor ou igual que'
    = f.text_field :maintenance_value_lteq
  .field
    = f.label :area_gteq, 'Área útil maior ou igual que'
    = f.text_field :area_gteq
  .field
    = f.label :area_lteq, 'Área útil menor ou igual que'
    = f.text_field :area_lteq
  .field
    = f.label :bedroom_gteq, 'Dormitórios maior ou igual que'
    = f.text_field :bedroom_gteq
  .field
    = f.label :bedroom_lteq, 'Dormitórios menor ou igual que'
    = f.text_field :bedroom_lteq
  .field
    = f.label :number_of_suites_gteq, 'Número de suites maior ou igual que'
    = f.text_field :number_of_suites_gteq
  .field
    = f.label :number_of_suites_lteq, 'Número de suítes menor ou igual que'
    = f.text_field :number_of_suites_lteq
  .field
    = f.label :number_of_parking_space_gteq, 'Número de vagas maior ou igual que'
    = f.text_field :number_of_parking_space_gteq
  .field
    = f.label :number_of_parking_space_lteq, 'Número de vagas menor ou igual que'
    = f.text_field :number_of_parking_space_lteq
  .actions
    = f.submit 'Pesquisar'

%table.properties
  %thead
    %tr
      %th= sort_link @search, :property_source_name, 'Site'
      %th= sort_link @search, :publish_date, 'Data'
      %th= sort_link @search, :type_of_property, 'Tipo'
      %th= sort_link @search, :city, 'Cidade'
      %th= sort_link @search, :neighborhood, 'Bairro'
      %th= sort_link @search, :sell_value, 'Valor' if @sell
      %th= sort_link @search, :rent_value, 'Valor' if @rent
      %th= sort_link @search, :maintenance_value, 'Condomínio'
      %th= sort_link @search, :area, 'Área'
      %th= sort_link @search, :bedroom, 'Quartos'
      %th= sort_link @search, :number_of_suites, 'Suítes'
      %th= sort_link @search, :number_of_parking_space, 'Vagas'
      %th
  %tbody
    - @properties.limit(100).each do |property|
      %tr
        %td= property.property_source.name
        %td= property.publish_date
        %td= property.type_of_property
        %td= property.city
        %td= property.neighborhood
        %td= property.sell_value
        %td= property.rent_value
        %td= property.maintenance_value
        %td= property.area
        %td= property.bedroom
        %td= property.number_of_suites
        %td= property.number_of_parking_space
        %td
          %a{:href => '#'} Ver detalhes